QuanLyNhaSach/QuanLyNhaSach/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyNhaSach.Models;

using PagedList;
using PagedList.Mvc;

namespace QuanLyNhaSach.Controllers
{
    public class BookStoreController : Controller
    {
        //tạo 1 đối tượng chứa toàn bộ csdl bán sách
        dbQLBansachDataContext data = new dbQLBansachDataContext();

        private List<SACH> Laysachmoi(int count)
        {
            //sắp xếp sách giảm dần theo Ngaycapnhat, lấy count dòng đầu
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }

        // GET: BookStore
        //public ActionResult Index()
        //{
            //Lấy 6 quyển sách mới nhất
        //    var sachmoi = Laysachmoi(6);
        //    return View(sachmoi);
        //}

        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }

        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }

        public ActionResult SPTheochude(int id, int? page)
        {
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int pageSize = 6;
            //tạo biến số trang
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }

        public ActionResult SPTheoNXB(int id, int? page)
        {
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int pageSize = 6;
            //tạo biến số trang
            int pageNum = (page ?? 1);
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach.ToPagedList(pageNum, pageSize));
        }

        public ActionResult Index(int? page)
        {
            //Tạo biến quy định số sản phẩm trên mỗi trang
            int pageSize = 6;
            //tạo biến số trang
            int pageNum = (page ?? 1);

            //lấy top 18 album bán chạy nhất
            var sachmoi = Laysachmoi(18);
            return View(sachmoi.ToPagedList(pageNum, pageSize));
        }
        public ActionResult Details (int id)
        {
            var sach = from s in data.SACHes where s.Masach == id select s;
            return View(sach.Single());
        }
    }
}

QuanLyNhaSach/QuanLyNhaSach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QuanLyNhaSach/QuanLyNhaSach/Views/Shared/_LayoutAdmin.cshtml
@using QuanLyNhaSach.Models;
@using PagedList.Mvc;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trang quản lý thư viện</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Jang Otoke", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Trang Chủ", "Index", "Admin")</li>
                    <li>@Html.ActionLink("Quản lý chủ đề", "Sanpham", "Admin")</li>
                    <li>@Html.ActionLink("Quản lý NXB", "Nhaxuatban", "Admin")</li>
                    <li>@Html.ActionLink("Quản lý Sách", "Sach", "Admin")</li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Đăng xuất", "Index", "BookStore")</li>
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dev by J.O aka Duyên</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

QuanLyNhaSach/QuanLyNhaSach/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Quản lý nhà sách</title>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
   
    <link rel="stylesheet" type="text/css" href="../../Content/style.css" />
    <!--[if IE 6]>
    <link rel="stylesheet" type="text/css" href="../../Content/iecss.css" />
    <![endif]-->
    <script type="text/javascript" src="../../Script/boxOver.js"></script>
</head>
<body>
    
    <div id="main_container">
        @RenderBody()
    </div>
    <!-- end of main_container -->
</body>
</html>